name: Docker publish

on:
  push:
    branches:
      - 'main'

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/checkout@v4
      - name: Set Git config
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - uses: extractions/setup-just@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          driver-opts: network=host

      - uses: actions/setup-go@v5
        with:
          go-version: '^1.24.x'

      - run: just dep patch

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish images
        run: just build
