name: Docker publish

on:
  push:
    branches:
      - 'main'

jobs:
  docker-image:
    runs-on: ubuntu-latest

    steps:
      - uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          driver-opts: network=host

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.22.x'

      - run: make dep patch

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Publish images
        env:
          IMAGE: ghcr.io/${{ github.repository }}
          GOLANG_IMAGE: golang:1.22-bullseye
        run: make build
